### ISSUE TITLE
Sameple Training Issue on Windows

### ISSUE THREAD

**Issue by jayahn77777** [vita-epfl/UniTraj#27]
I want to make sure Unitraj Installation properly.
So, I tried "python train.py method=autobot" command, I got below error.

Sanity Checking: |                                                                                                                                                                                                    | 0/? [00:00<?, ?it/s]C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=23` in the `DataLoader` to improve performance.
Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                   | 0/1 [00:00<?, ?it/s]C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\torch\nn\functional.py:5560: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
Error executing job with overrides: ['method=autobot']
Traceback (most recent call last):
  File "D:\Coding\Anaconda\UniTraj_01\UniTraj\unitraj\train.py", line 65, in train
    trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=val_loader, ckpt_path=cfg.ckpt_path)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 574, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 981, in _run
    results = self._run_stage()
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1023, in _run_stage
    self._run_sanity_check()
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1052, in _run_sanity_check
    val_loop.run()
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\loops\utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\trainer\call.py", line 319, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 411, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "d:\coding\anaconda\unitraj_01\unitraj\unitraj\models\base_model\base_model.py", line 60, in validation_step
    self.log_info(batch, batch_idx, prediction, status='val')
  File "d:\coding\anaconda\unitraj_01\unitraj\unitraj\models\base_model\base_model.py", line 267, in log_info
    wandb.log({"prediction": [wandb.Image(img)]})
  File "C:\Users\XXX\.conda\envs\unitraj\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I want to know how I can find HYDRA_FULL_ERROR variable....
Where is it..?

**Comment by Alan-LanFeng** [comment]
it's a wandb bug and has been fixed recently, please pull the latest code then retry
