### ISSUE TITLE
MTR Training issue with CYCLIST and PEDESTRIAN

### ISSUE THREAD

**Issue by bob020416** [vita-epfl/UniTraj#40]
Hi i correctly set up my own dataset in scenarionet format, but when i tried to train it using MTR it shows the following error, i tried it with the sample set using nuscenes also encounter this error, and looks like the original config file you have disable CYCLIST and PEDESTRIAN is it because they are not support now during training ? 

```
python train.py method=MTR
/home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
Seed set to 42
Error executing job with overrides: ['method=MTR']
Traceback (most recent call last):
  File "/home/yhchen/Documents/Scenarionet/UniTraj/unitraj/train.py", line 22, in train
    model = build_model(cfg)
  File "/home/yhchen/Documents/Scenarionet/UniTraj/unitraj/models/__init__.py", line 13, in build_model
    model = __all__[config.method.model_name](
  File "/home/yhchen/Documents/Scenarionet/UniTraj/unitraj/models/mtr/MTR.py", line 39, in __init__
    self.motion_decoder = MTRDecoder(
  File "/home/yhchen/Documents/Scenarionet/UniTraj/unitraj/models/mtr/MTR.py", line 324, in __init__
    self.intention_points, self.intention_query, self.intention_query_mlps = self.build_motion_query(
  File "/home/yhchen/Documents/Scenarionet/UniTraj/unitraj/models/mtr/MTR.py", line 386, in build_motion_query
    cur_intention_points = intention_points_dict[cur_type]
KeyError: 'PEDESTRIAN'

```

below is my config file:

```
# exp setting
exp_name: 'test2' # name that will be used in wandb
ckpt_path: 'lightning_logs/version_6/checkpoints/epoch=135-val/brier_fde=7.08.ckpt' # checkpoint path, used for evaluation
seed: 42 # random seed
debug: True # debug mode, will use cpu only
devices: [ 0 ] # gpu ids

# data related
load_num_workers: 0 # number of workers for loading data
train_data_path: [ "data_samples/taiwan_train" ] # list of paths to the training data
val_data_path: [ "data_samples/taiwan_validate" ] # list of paths to the validation data
max_data_num: [ 100000] # maximum number of data for each training dataset
starting_frame: [ 0 ] # history trajectory starts at this frame for each training dataset
past_len: 100 # history trajectory length, 2.1s
future_len: 100 # future trajectory length, 6s
object_type: [ 'VEHICLE' , 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump' ] # line type to be considered in the input
masked_attributes: [ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 0.0, 0.0 ] # center offset of the map
use_cache: False # use cache for data loading
overwrite_cache: True # overwrite existing cache
store_data_in_memory: False # store data in memory

# official evaluation
nuscenes_dataroot: '/mnt/nas3_rcp_enac_u0900_vita_scratch/datasets/Prediction-Dataset/nuscenes/nuscenes_root'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool

defaults:
  - method: autobot
```

Some training log in autobot 

```
Loaded 152 samples from data_samples/taiwan_train
Data loaded
Loading validation data...
Using 19 processes to load data...
0/4 data processed
Loaded 152 samples from data_samples/taiwan_validate
Data loaded
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
2024-11-27 18:33:29.334501: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-27 18:33:29.458822: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/cv2/../../lib64:/home/yhchen/miniconda3/envs/habitat/lib:/usr/local/cuda-12.4/lib64
2024-11-27 18:33:29.458847: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-11-27 18:33:30.061393: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/cv2/../../lib64:/home/yhchen/miniconda3/envs/habitat/lib:/usr/local/cuda-12.4/lib64
2024-11-27 18:33:30.061506: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/cv2/../../lib64:/home/yhchen/miniconda3/envs/habitat/lib:/usr/local/cuda-12.4/lib64
2024-11-27 18:33:30.061517: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
/home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:62: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

   | Name                   | Type               | Params  | Mode 
------------------------------------------------------------------------
0  | agents_dynamic_encoder | Sequential         | 384     | train
1  | temporal_attn_layers   | ModuleList         | 330 K   | train
2  | social_attn_layers     | ModuleList         | 330 K   | train
3  | map_encoder            | MapEncoderPts      | 100.0 K | train
4  | map_attn_layers        | MultiheadAttention | 66.0 K  | train
5  | tx_decoder             | ModuleList         | 463 K   | train
6  | pos_encoder            | PositionalEncoding | 12.8 K  | train
7  | output_model           | OutputModel        | 33.7 K  | train
8  | mode_map_attn          | MultiheadAttention | 66.0 K  | train
9  | prob_decoder           | MultiheadAttention | 66.0 K  | train
10 | prob_predictor         | Linear             | 129     | train
11 | criterion              | Criterion          | 0       | train
   | other params           | n/a                | 77.6 K  | n/a  
------------------------------------------------------------------------
1.5 M     Trainable params
12.8 K    Non-trainable params
1.5 M     Total params
6.190     Total estimated model params size (MB)
110       Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                                                                | 0/? [00:00<?, ?it/s]/home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=19` in the `DataLoader` to improve performance.
Sanity Checking DataLoader 0:   0%|                                                                                               | 0/1 [00:00<?, ?it/s]wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: bob020416-cs13 (bob020416-cs13-national-yang-ming-chiao-tung-university). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.7
wandb: Run data is saved locally in /home/yhchen/Documents/Scenarionet/UniTraj/unitraj/wandb/run-20241127_183333-test2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run test2
wandb: ⭐️ View project at https://wandb.ai/bob020416-cs13-national-yang-ming-chiao-tung-university/unitraj
wandb: 🚀 View run at https://wandb.ai/bob020416-cs13-national-yang-ming-chiao-tung-university/unitraj/runs/test2
/home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=19` in the `DataLoader` to improve performance.
/home/yhchen/miniconda3/envs/scenarionet/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_ste
```

Again thanks for your help, this works really helps a lot

**Comment by bob020416** [comment]
thank you, i'll try it out. 

also i want to ask is your repository still being update? 
there is a prediction visualization part in the evaluation, but it's now gone. 

Thanks !

**Comment by Alan-LanFeng** [comment]
Yes, we temporarily commented the visualization code as it seems to cause some issues.

**Comment by bob020416** [comment]
thanks i'll wait until then,

can we expect that visualization can come with a feature maybe inference and get a video of the prediction result ? 

Again, Thank you this project really helps a lot

**Comment by Alan-LanFeng** [comment]
Yes. The visualization is a cool feature. I'll try to add it in the future.

**Comment by aselimc** [comment]
Hello, @Alan-LanFeng did you have a time to look at the visualization?
